"""Session 13 — Report Narrative Agent: LLM-generated per-section prose.

Replaces hardcoded section strings in ReportAssemblyService with
institutionally-worded narrative paragraphs generated by the LLM.

The agent is called once per run and produces all report narrative sections
in a single LLM call, returning a structured dict keyed by section name.
Output is used by ReportAssemblyService.assemble_report() to populate the
Jinja2 template.
"""
from __future__ import annotations

import json
import logging
from typing import Any

from research_pipeline.agents.base_agent import BaseAgent

logger = logging.getLogger(__name__)

# Section keys produced by this agent
NARRATIVE_SECTIONS = [
    "executive_summary",
    "methodology",
    "valuation_appendix",
    "risk_appendix",
    "self_audit_appendix",
]


class ReportNarrativeAgent(BaseAgent):
    """Generate JPAM-style narrative prose for all report sections in one pass.

    Input: structured run outputs (portfolio, valuations, risk, macro, ESG, etc.)
    Output: dict with one narrative string per section — no hardcoded strings.

    Session 13: elevates reports from template-filled stubs to institutionally
    publishable prose that references actual run data.
    """

    _REQUIRED_OUTPUT_KEYS: list[str] = ["executive_summary", "methodology"]
    _VALIDATION_FATAL: bool = False   # Narrative failure is non-blocking

    def __init__(self, **kwargs):
        super().__init__(name="report_narrative", **kwargs)

    def default_system_prompt(self) -> str:
        return """You are the Report Narrative Writer for a JP Morgan Asset Management
institutional research platform.

Your role: take structured pipeline outputs (sector analysis, valuations, risk metrics,
portfolio weights, ESG scores, macro regime) and write polished, institution-grade
narrative prose for each section of the research report.

WRITING STYLE:
- JPAM/Goldman Sachs house style: precise, evidence-referenced, no weasel words
- Use present tense for current holdings, past tense for historical comparisons
- Cite specific data points: "NVDA implied return of +42% on our base case DCF"
- Metrics must match numbers in the structured data provided — no hallucination
- Paragraph length: 3-5 sentences per section. No bullet points in the narrative.
- Tone: confident institutional, not hedged marketing copy

SECTIONS TO WRITE:
1. executive_summary: 3-4 sentences summarising thesis, portfolio stance, key risks
2. methodology: 2-3 sentences describing the 15-stage pipeline approach and data sources
3. valuation_appendix: 2-3 sentences on valuation methodology (DCF, EV/EBITDA, P/E, sensitivity)
4. risk_appendix: 2-3 sentences on VaR framework, stress testing, macro scenario overlay
5. self_audit_appendix: 1-2 sentences on claim classification and evidence tiering

MACRO INTEGRATION (Session 13):
When MACRO REGIME CONTEXT is provided in the input:
- Reference current rate regime explicitly in executive_summary
- Note AU/US macro divergence if relevant to portfolio positioning
- Mention scenario type (base/bull/bear) and its implication for return expectations

OUTPUT FORMAT:
Return a single JSON object:
{
  "executive_summary": "...",
  "methodology": "...",
  "valuation_appendix": "...",
  "risk_appendix": "...",
  "self_audit_appendix": "..."
}

Every section MUST be a non-empty string. No null values.
Do not add any keys outside those five."""

    def format_input(self, inputs: dict[str, Any]) -> str:
        """Inject macro header and format pipeline outputs for narrative generation."""
        macro_header = self._build_macro_header(inputs)
        # Extract key summary data to keep the prompt focused
        summary: dict[str, Any] = {
            "run_id": inputs.get("run_id", ""),
            "tickers": inputs.get("tickers", []),
            "publication_status": inputs.get("publication_status", ""),
            "macro_regime": inputs.get("macro_regime", inputs.get("regime_classification", "")),
        }
        # Portfolio
        if "portfolios" in inputs:
            portfolios = inputs["portfolios"]
            if isinstance(portfolios, list) and portfolios:
                bal = next((p for p in portfolios if "balanced" in str(p.get("variant", ""))), portfolios[0])
                summary["balanced_portfolio_top5"] = (bal.get("positions") or [])[:5]
        elif "portfolio_weights" in inputs:
            summary["portfolio_weights"] = inputs["portfolio_weights"]
        # Valuations
        if "valuations" in inputs:
            vals = inputs["valuations"]
            if isinstance(vals, list):
                summary["valuation_snapshot"] = [
                    {
                        "ticker": v.get("ticker"),
                        "entry_quality": v.get("entry_quality"),
                        "scenarios": (v.get("section_5_scenarios") or [])[:2],
                    }
                    for v in vals[:5] if isinstance(v, dict)
                ]
        # Risk
        for k in ("var_95", "cvar_95", "max_drawdown", "overall_risk_level", "portfolio_var_95"):
            if k in inputs:
                summary[k] = inputs[k]
        # Economy analysis
        if "economy_analysis" in inputs:
            ea = inputs["economy_analysis"]
            if isinstance(ea, dict):
                summary["economy_summary"] = {
                    "rba_thesis": ea.get("rba_cash_rate_thesis", "")[:200],
                    "fed_thesis": ea.get("fed_funds_thesis", "")[:200],
                    "au_risks": (ea.get("key_risks_au") or [])[:3],
                }

        body = json.dumps(summary, indent=2, default=str)
        if macro_header:
            return f"{macro_header}\n\n{body}"
        return body

    def parse_output(self, raw_response: str) -> dict[str, Any]:
        """Ensure all required narrative sections are present and non-empty."""
        parsed = super().parse_output(raw_response)

        if not isinstance(parsed, dict):
            # If model returned a list, try extracting first element
            if isinstance(parsed, list) and parsed and isinstance(parsed[0], dict):
                parsed = parsed[0]
            else:
                parsed = {}

        # Fill any missing sections with a placeholder rather than failing
        for section in NARRATIVE_SECTIONS:
            if not parsed.get(section):
                parsed[section] = (
                    f"[{section.replace('_', ' ').title()} — narrative generation "
                    "incomplete; see structured data appendix.]"
                )

        return parsed

    async def generate_narrative(
        self,
        run_id: str,
        pipeline_outputs: dict[str, Any],
    ) -> dict[str, str]:
        """Convenience wrapper: run agent and return narrative sections dict.

        Never raises. On failure returns placeholder strings for all sections.
        """
        try:
            result = await self.run(run_id, pipeline_outputs)
            if result.success and isinstance(result.parsed_output, dict):
                return {k: str(v) for k, v in result.parsed_output.items() if k in NARRATIVE_SECTIONS}
        except Exception as exc:
            logger.warning("ReportNarrativeAgent: failed for run %s: %s", run_id, exc)

        return {
            section: (
                f"[{section.replace('_', ' ').title()} — generated automatically "
                f"from run {run_id}. Narrative generation unavailable.]"
            )
            for section in NARRATIVE_SECTIONS
        }
